from pathlib import Path
from time import time

from mctools.common.risk.scenario import Scenario
from mctools.common.risk.value import Value


def getPrintedValue(val=None, err=None, value: Value | None = None):
    """Return a string with the value to be printed

    If value is zero, no error is printed
    """
    if value is not None:
        val = value.val
        err = value.err

    epsilon = 1e-10
    color = ""
    bigerror = ""
    if val > 0.25:
        color = "[color=abovequater]"
    if val > 0.5:
        color = "[color=abovehalf]"

    if abs(val) > epsilon and err / val > 0.2:
        bigerror = " \\bigerror"
    return (
        "\\num{0.0}"
        if abs(val) < epsilon
        else "\\num%s{%f +- %f}%s" % (color, val, err, bigerror)
    )


class Case:
    def __init__(self, scenarios: list[Scenario], name: str = ""):
        self.name = name
        self.scenarios = scenarios

    def evaluate(self):
        for scenario in self.scenarios:
            scenario.evaluate()

    def toLaTeX(
        self,
        command_output_file_name: Path,
        variable_output_file_name: Path,
    ):
        commands = self.createLaTeXCommands()
        with open(
            command_output_file_name, "w", encoding="utf-8"
        ) as command_output_file:
            command_output_file.write(commands)

        variables = self.createAllVariableLaTeX(
            command_output_file_name=command_output_file_name
        )
        with open(
            variable_output_file_name, "w", encoding="utf-8"
        ) as variable_output_file:
            variable_output_file.write(variables)
        print(
            f"Created output file '{variable_output_file_name}' which calls "
            r"the \rate command for all possible arguments."
            "\n"
            r"It is assumed that the \rate commands are defined in a file "
            f"called '{command_output_file_name}'."
            "\nBuild document with\n\t"
            f"LATEX {variable_output_file_name} && "
            f"LATEX {variable_output_file_name}\n"
            "where LATEX is your LATEX compiler.\n"
            "(LATEX is invoked twice to build the table of contents.)"
        )

    def createLaTeXCommands(self) -> str:
        buffer = [
            "% This file is generated by getmax.py. Don't edit it by hand.\n"
            "\\definecolor{abovequater}{HTML}{ff8b00} % for dose rates > 0.25 uSv/h\n"
            "\\definecolor{abovehalf}{HTML}{ff0000}   % for dose rates > 0.5 uSv/h\n"
            "\\newcommand\\bigerror{\\textcolor{red}{(BIG ERROR!)}}\n"
            "\\NewDocumentCommand\\rate{mmmmg}{%\n"
            "  % 1: scenario\n"
            "  % 2: region\n"
            "  % 3: area\n"
            "  % 4: zone\n"
        ]

        for scenario in self.scenarios:
            buffer.append(
                r"\ifthenelse{\equal{#1}{"
                f"{scenario.name}"
                "}}{% "
                f"{scenario.name}\n"
            )
            for region in scenario.data.sources:
                buffer.append(
                    r"  \ifthenelse{\equal{#2}{"
                    f"{region}"
                    "}}{% "
                    f"{scenario[region].path}\n"
                )
                for area in scenario.data.sources[region].sub_levels:
                    buffer.append(
                        r"    \ifthenelse{\equal"
                        "{#3}{" + f"{area}"
                        "}}{% "
                        f"{scenario[region][area].path}\n"
                    )
                    for zone in (
                        scenario.data.sources[region].sub_levels[area].sub_levels
                    ):
                        buffer.append(
                            r"      \ifthenelse{\equal{#4}{"
                            f"{zone}"
                            "}}{"
                            f"{getPrintedValue(value=scenario[region][area][zone].value)}"
                            "}{"
                            f"% {scenario[region][area][zone].path}\n"
                        )
                    buffer.append(
                        "        "
                        + (
                            "}"
                            * len(
                                scenario.data.sources[region]
                                .sub_levels[area]
                                .sub_levels
                            )
                        )
                        + "\n"
                    )
                    buffer.append("      }{}%\n")
                buffer.append("    }{}%\n")
            buffer.append("  }{%\n")
            for combo in scenario.data.cross_level_combinations:
                buffer.append(
                    r"\ifthenelse{\equal{#1}{"
                    f"{combo}"
                    "}}{% "
                    f"{combo}\n"
                    f"{getPrintedValue(value=scenario[combo].value)}"
                )
                buffer.append("}{}\n")
            buffer.append("}%\n")
        buffer.append("}%\n")
        return "".join(buffer)

    def createAllVariableLaTeX(self, command_output_file_name: Path) -> str:
        buffer = [
            r"\documentclass{article}"
            "\n\n"
            r"\usepackage[margin=1in]{geometry}"
            "\n"
            r"\usepackage{ifthen}"
            "\n"
            r"\usepackage{siunitx}"
            "\n"
            r"\sisetup{round-mode = uncertainty, round-precision = 1}"
            "\n"
            r"\usepackage{tikz}"
            "\n"
            "\n"
            r"\usepackage{xstring}"
            "\n"
            "\n"
            r"\usepackage{xparse}"
            "\n\n"
            r"\setlength\parindent{0pt}"
            "\n\n"
            r"\input{"
            f"{command_output_file_name}"
            "}\n\n"
            r"\newcommand\print{%"
            "\n"
            r"  \scenario.\region.\area.\zone : \value"
            "\n}\n"
            r"\newcommand\printCombo{%"
            "\n"
            r"  \combo : \value"
            "\n}\n\n"
            r"\begin{document}"
            "\n"
            r"\tableofcontents"
            "\n"
        ]

        for scenario in self.scenarios:
            buffer.append(r"\section{" f"{scenario.name}" "}")
            buffer.append(r"\def\scenario{" f"{scenario.name}" "}\n")
            for region in scenario.data.sources:
                buffer.append(r"\def\region{" f"{region}" "}\n")
                for area in scenario.data.sources[region].sub_levels:
                    buffer.append(r"\def\area{" f"{area}" "}\n")
                    for zone in (
                        scenario.data.sources[region].sub_levels[area].sub_levels
                    ):
                        buffer.append(r"\def\zone{" f"{zone}" "}\n")
                        buffer.append(
                            r"\def\value{\rate{"
                            f"{scenario.name}"
                            "}{"
                            f"{region}"
                            "}{"
                            f"{area}"
                            "}{"
                            f"{zone}"
                            "}}\n"
                            r"\print"
                            "\n\n"
                        )
            for combo in scenario.data.cross_level_combinations:
                buffer.append(r"\def\combo{" f"{combo}" "}\n")
                buffer.append(
                    r"\def\value{\rate{" f"{combo}" "}{}{}{}}\n" r"\printCombo" "\n\n"
                )
        buffer.append(r"\end{document}")
        return "".join(buffer)
